language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
before_script:
  - cp config/config.travis.yml config/config.yml
services:
  - rabbitmq
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: 2b18233b4edb7538d4bc02a17fa9c6041e08af33e7ffeb19f1c96fd4e6bcc141