default: &default
  application_name: GoogleDirectoryDaemon-test
  application_id: gdd

  rabbitmq_host: localhost
  rabbitmq_port: 5672
  rabbitmq_vhost: /
  rabbitmq_queue_name: gdirdaemon
  rabbitmq_deferred_time: 1800000
  rabbitmq_max_attempts: 48
  rabbitmq_event_exchange_name: agoram_event_exchange
  rabbitmq_user: guest
  rabbitmq_password: guest

  log_routing_key: "logging.key"

  ldap_host: localhost
  ldap_port: 389
  ldap_base: dc=mycompany,dc=org
  ldap_bind_dn: cn=myuser,dc=mycompany,dc=org
  ldap_password: P4ssWord
  ldap_connection_method: plain #or ssl, tls

  mailchimp_api_user: ""
  mailchimp_api_password: ""

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
