default: &default
  application_name: GorgLdapDaemon
  application_id: ldapd-t

  rabbitmq_host: localhost
  rabbitmq_port: 5672
  rabbitmq_vhost: /
  rabbitmq_queue_name: ldapd
  rabbitmq_exchange_name: agoram_event_exchange
  rabbitmq_deferred_time: 1000
  rabbitmq_max_attempts: 5
  rabbitmq_user: guest
  rabbitmq_password: guest


  log_routing_key: "agoram.log"

  gram_api_host: https://gram-api-2.herokuapp.com/api/v2/
  gram_api_user: 
  gram_api_password: 

  
  ldap_host: theia.gorgu.net
  ldap_port: 390
  ldap_base: ou=gram,dc=gadz,dc=org
  ldap_bind_dn: 
  ldap_password: 

development:
  <<: *default
